name: Prettier Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check code style
        run: prettier --check '**/*.js' --write

      - name: Fail if any files need formatting
        if: steps.prettier-check.outputs.incorrect-files != ''
        run: |
          echo "The following files need to be formatted:"
          echo "${steps.prettier-check.outputs.incorrect-files}"
          exit 1
